language: node_js
node_js:
  - 6
  - 8
  - 10
  - 12
  - node
cache:
  directories:
    - "node_modules"
services:
  - mongodb

script: "npm run ci"
after_script: "npm install coveralls@2.13.1 && cat ./coverage/lcov.info | coveralls"