language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
cache:
  directories:
    - "node_modules"
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.13.1 && cat ./coverage/lcov.info | coveralls"