name: Release & Publish

on:
  push:
    tags:
      - 'release/v*'

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Prettier
        run: npm run prettier

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test:coverage

      - name: e2e tests
        run: npm run test:e2e:docker
        timeout-minutes: 3

      - name: Get version
        run: echo "::set-output name=NPM_VERSION::${GITHUB_REF#refs/*/v}"
        id: npm-version

      - name: Set version
        run: npm version ${{steps.npm-version.outputs.NPM_VERSION}} --no-commit-hooks --no-git-tag-version --allow-same-version

      - name: NPM Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Zip artifacts
        run: |
          zip -r ${{ github.event.repository.name }}.${{steps.npm-version.outputs.NPM_VERSION}}.zip \
          README.md \
          LICENSE \
          package.json \
          dist

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{steps.npm-version.outputs.NPM_VERSION}}
          files: |
            ${{ github.event.repository.name }}.${{steps.npm-version.outputs.NPM_VERSION}}.zip
